const seed={
 activeBusinessId:'caravan',company:{name:'Golden Sands Trading Company',owner:"Ko'vash",caravanCut:20},
 businesses:[
  {id:'caravan',name:'Golden Sands Caravan',type:'Caravan',hold:'The Pale',location:'Dawnstar market camp',description:'Primary travelling caravan and trade hub.',status:'Active',coffers:12450},
  {id:'farm',name:'Golden Sands Farm',type:'Farm',hold:'The Pale',location:'Outside Dawnstar',description:'Company farm supplying produce and ingredients.',status:'Active',coffers:3820},
  {id:'inn',name:'Future Golden Sands Inn',type:'Inn',hold:'Unassigned',location:'Unassigned',description:'Future hospitality business.',status:'Inactive',coffers:0}
 ],
 employees:[
  {id:1,name:"Ko'vash",email:'owner@example.com',role:'Company Owner',earnings:0,assignments:{caravan:{enabled:true,permissions:['all']},farm:{enabled:true,permissions:['all']},inn:{enabled:true,permissions:['all']}}},
  {id:2,name:"Ra'zirr",email:'razirr@example.com',role:'Merchant',earnings:3250,assignments:{caravan:{enabled:true,permissions:['register','inventory_view','orders','notebook','tasks']},farm:{enabled:false,permissions:[]},inn:{enabled:false,permissions:[]}}},
  {id:3,name:"M'aiqra",email:'maiqra@example.com',role:'Caravan Hand',earnings:1480,assignments:{caravan:{enabled:true,permissions:['inventory_view','transfers','notebook','tasks']},farm:{enabled:true,permissions:['inventory_view','inventory_edit','transfers','tasks']},inn:{enabled:false,permissions:[]}}}
 ],
 inventory:[
  {id:1,businessId:'caravan',name:'Moon Monk Robes',category:'Apparel',condition:'Exquisite',qty:4,price:1650,batches:[{batchId:'b1',qty:4,contributorId:2,source:'Stock Intake'}]},
  {id:2,businessId:'caravan',name:'Khajiit Merchant Robes',category:'Apparel',condition:'Fine',qty:7,price:900,batches:[{batchId:'b2',qty:5,contributorId:1,source:'Stock Intake'},{batchId:'b3',qty:2,contributorId:3,source:'Transfer from Farm'}]},
  {id:3,businessId:'caravan',name:'Moon Sugar',category:'Ingredient',condition:'Standard',qty:23,price:95,batches:[{batchId:'b4',qty:15,contributorId:2,source:'Stock Intake'},{batchId:'b5',qty:8,contributorId:3,source:'Stock Intake'}]},
  {id:4,businessId:'farm',name:'Potato',category:'Produce',condition:'Fresh',qty:48,price:12,batches:[{batchId:'b6',qty:48,contributorId:3,source:'Harvest / Intake'}]}
 ],
 notes:[{id:1,author:"Ra'zirr",date:'16th of Last Seed',businessId:'caravan',text:'A hunter near Whiterun claims he will have ten wolf pelts tomorrow.',pinned:true}],
 history:[],transfers:[]
};
let state=JSON.parse(localStorage.getItem('gsl-phase4')||'null')||structuredClone(seed);let cart=[],currentView='company';
const $=s=>document.querySelector(s),app=$('#app');
const permissionLabels={register:'Use Register',inventory_view:'View Inventory',inventory_edit:'Edit Inventory',orders:'Create / Complete Orders',transfers:'Transfer Stock',suppliers:'Manage Suppliers',notebook:'Use Notebook',tasks:'Use Tasks',coffers:'View Coffers',coffers_edit:'Modify Coffers',employees:'Manage Employees',permissions:'Change Permissions'};
const navGroups=[['Company',[['company','◈','Company Overview'],['businesses','⌂','Businesses']]],['Current Business',[['dashboard','⌂','Dashboard'],['register','✦','Register'],['inventory','▦','Inventory'],['transfers','⇄','Transfers']]],['Caravan',[['notebook','✎','Notebook'],['employees','♟','Employees']]],['Accounting',[['coffers','◈','Coffers'],['history','≡','Sales History'],['earnings','¤','Employee Earnings']]],['Administration',[['permissions','⚙','Permissions'],['settings','☼','Settings']]]];
function save(){localStorage.setItem('gsl-phase4',JSON.stringify(state))}function money(n){return Number(n||0).toLocaleString()+' septims'}function activeBusiness(){return state.businesses.find(b=>b.id===state.activeBusinessId)||state.businesses[0]}function inv(){return state.inventory.filter(i=>i.businessId===state.activeBusinessId)}function empName(id){return state.employees.find(e=>e.id===id)?.name||'Unknown'}function bizName(id){return state.businesses.find(b=>b.id===id)?.name||id}function eligibleEmployees(bid=state.activeBusinessId){return state.employees.filter(e=>e.assignments?.[bid]?.enabled)}function now(){return new Date().toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function setHead(t,e){$('#pageTitle').textContent=t;$('#eyebrow').textContent=e||activeBusiness().name;$('#pageActions').innerHTML=''}function stat(l,v,s,i='◈'){return `<div class="card stat"><span class="sigil">${i}</span><div class="label">${l}</div><div class="value">${v}</div><div class="sub">${s}</div></div>`}function table(h,r){return `<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.join('')}</tbody></table></div>`}
function buildNav(){$('#nav').innerHTML=navGroups.map(([g,items])=>`<div class="nav-group-title">${g}</div>${items.map(([v,i,l])=>`<button class="nav-item ${currentView===v?'active':''}" data-view="${v}"><span>${i}</span>${l}</button>`).join('')}`).join('');document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view))}
function buildBusinessSelect(){const s=$('#businessSelect');const actives=state.businesses.filter(b=>b.status==='Active');if(!actives.some(b=>b.id===state.activeBusinessId)&&actives[0])state.activeBusinessId=actives[0].id;s.innerHTML=actives.map(b=>`<option value="${b.id}" ${b.id===state.activeBusinessId?'selected':''}>${b.name}</option>`).join('');$('#businessLocation').textContent=`${activeBusiness().hold} · ${activeBusiness().location}`;s.onchange=()=>{state.activeBusinessId=s.value;save();buildBusinessSelect();render();renderNotebookPreview()}}
function renderNotebookPreview(){const ns=state.notes.filter(n=>n.businessId===state.activeBusinessId).slice(0,3);$('#notebookPreview').innerHTML=ns.length?ns.map(n=>`<div class="note-preview"><strong>${n.author}</strong><time>${n.date}</time><p>${n.text}</p></div>`).join(''):'<div class="empty">No notes.</div>'}
function go(v){currentView=v;buildNav();render();closeNav()}window.go=go;function closeNav(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}$('#navToggle').onclick=()=>{$('#sidebar').classList.toggle('open');$('#backdrop').classList.toggle('show')};$('#backdrop').onclick=closeNav;
function render(){({company,businesses,dashboard,register,inventory,transfers,notebook,employees,coffers,history,earnings,permissions,settings}[currentView])();renderNotebookPreview()}
function company(){setHead('Company Overview','Golden Sands Trading Company');app.innerHTML=`<div class="grid g4">${stat('Company Coffers',money(state.businesses.reduce((a,b)=>a+b.coffers,0)),'Across all businesses')}${stat('Active Businesses',state.businesses.filter(b=>b.status==='Active').length,'Currently operating','⌂')}${stat('Employees',state.employees.length,'Company members','♟')}${stat('Inventory Units',state.inventory.reduce((a,b)=>a+b.qty,0),'Across all businesses','▦')}</div>`}
function businesses(){setHead('Businesses','Company Structure');$('#pageActions').innerHTML='<button class="btn" onclick="addBusiness()">+ Add Business</button>';app.innerHTML=`<div class="business-grid">${state.businesses.map(b=>`<div class="business-card"><span class="eyebrow">${b.type}</span><h3>${b.name}</h3><p><strong>Status:</strong> ${b.status}<br><strong>Hold:</strong> ${b.hold}<br><strong>Location:</strong> ${b.location}<br>${b.description}</p><div class="quick"><button class="btn secondary" onclick="switchBusiness('${b.id}')">Open</button><button class="btn ghost" onclick="editBusiness('${b.id}')">Edit</button></div></div>`).join('')}</div>`}
window.switchBusiness=id=>{state.activeBusinessId=id;save();buildBusinessSelect();go('dashboard')};window.addBusiness=()=>businessModal(null);window.editBusiness=id=>businessModal(state.businesses.find(b=>b.id===id));
function businessModal(b){modal(b?'Edit Business':'Add Business',`<div class="form-grid"><div class="field span2"><label>Name</label><input id="bName" class="input" value="${b?.name||''}"></div><div class="field"><label>Type</label><input id="bType" class="input" value="${b?.type||'Shop'}"></div><div class="field"><label>Status</label><select id="bStatus" class="select"><option ${b?.status==='Active'?'selected':''}>Active</option><option ${b?.status==='Inactive'?'selected':''}>Inactive</option></select></div><div class="field"><label>Hold</label><input id="bHold" class="input" value="${b?.hold||''}"></div><div class="field"><label>Location</label><input id="bLoc" class="input" value="${b?.location||''}"></div><div class="field span2"><label>Description</label><textarea id="bDesc" class="textarea">${b?.description||''}</textarea></div></div>`,()=>{const name=$('#bName').value.trim();if(!name)return;if(b){Object.assign(b,{name,type:$('#bType').value||'Shop',status:$('#bStatus').value,hold:$('#bHold').value||'Unassigned',location:$('#bLoc').value||'Unassigned',description:$('#bDesc').value||''})}else{const id='biz'+Date.now();state.businesses.push({id,name,type:$('#bType').value||'Shop',status:$('#bStatus').value,hold:$('#bHold').value||'Unassigned',location:$('#bLoc').value||'Unassigned',description:$('#bDesc').value||'',coffers:0});state.employees.forEach(e=>e.assignments[id]={enabled:false,permissions:[]})}save();closeModal();buildBusinessSelect();render()})}
function dashboard(){setHead('Dashboard',activeBusiness().name);app.innerHTML=`<div class="grid g4">${stat('Coffers',money(activeBusiness().coffers),'Business balance')}${stat('Stock Units',inv().reduce((a,b)=>a+b.qty,0),inv().length+' item entries','▦')}${stat('Assigned Employees',eligibleEmployees().length,'Can work here','♟')}${stat('Stock Contributors',new Set(inv().flatMap(i=>i.batches.map(b=>b.contributorId))).size,'Represented in stock','✦')}</div>`}
function register(){setHead('Register','Point of Sale · '+activeBusiness().name);app.innerHTML=`<div class="register-grid"><div class="card"><div class="toolbar"><input id="itemSearch" class="input search" placeholder="Search wares…"></div><div id="itemGrid" class="item-grid"></div></div><div><div class="card"><h3>Current Sale</h3><div id="cart"></div></div><div id="receiptPreview" class="receipt" style="margin-top:12px"></div></div></div>`;$('#itemSearch').oninput=drawItems;drawItems();drawCart()}
function drawItems(){const q=($('#itemSearch')?.value||'').toLowerCase();const items=inv().filter(i=>i.qty>0&&(i.name+' '+i.condition).toLowerCase().includes(q));$('#itemGrid').innerHTML=items.map(i=>`<button class="item" onclick="addCart(${i.id})"><strong>${i.name}</strong><small>${i.category} · ${i.condition} · ${i.qty} available</small><div class="price">${money(i.price)}</div></button>`).join('')||'<div class="empty">No wares.</div>'}
window.addCart=id=>{const i=state.inventory.find(x=>x.id===id),c=cart.find(x=>x.id===id);if(c){if(c.qty<i.qty)c.qty++}else cart.push({id:i.id,name:i.name,price:i.price,qty:1});drawCart()};window.cartQty=(id,d)=>{const c=cart.find(x=>x.id===id),i=state.inventory.find(x=>x.id===id);c.qty=Math.max(0,Math.min(i.qty,c.qty+d));if(c.qty===0)cart=cart.filter(x=>x.id!==id);drawCart()};
function previewContributors(){const map=new Map();for(const c of cart){const item=state.inventory.find(i=>i.id===c.id);let need=c.qty;for(const b of item.batches){if(need<=0)break;const used=Math.min(need,b.qty);if(used>0){map.set(b.contributorId,(map.get(b.contributorId)||0)+used);need-=used}}}return [...map.entries()].map(([id,units])=>({id,name:empName(id),units}))}
function calcReceipt(){const subtotal=cart.reduce((a,b)=>a+b.price*b.qty,0),discount=Math.max(0,Math.min(100,Number($('#discount')?.value)||0)),sale=Math.round(subtotal*(1-discount/100)),cut=Math.round(sale*(state.company.caravanCut/100));return{subtotal,discount,sale,cut,pool:sale-cut}}
function drawCart(){const el=$('#cart');if(!el)return;el.innerHTML=cart.length?cart.map(c=>`<div class="cart-row"><div><strong>${c.name}</strong><small>${money(c.price)} each</small></div><div class="qty-controls"><button class="qty" onclick="cartQty(${c.id},-1)">−</button><strong>${c.qty}</strong><button class="qty" onclick="cartQty(${c.id},1)">+</button></div></div>`).join(''):'<div class="empty">No items added.</div>';const es=eligibleEmployees();el.innerHTML+=`<div class="form-grid" style="margin-top:12px"><div class="field"><label>Discount %</label><input id="discount" class="input" type="number" min="0" max="100" value="0"></div><div class="field"><label>Seller / Cashier</label><select id="seller" class="select">${es.map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select></div></div><div class="field" style="margin-top:10px"><label>Additional Participants</label><div class="permission-grid">${es.map(e=>`<label class="perm"><input class="extraPart" type="checkbox" value="${e.id}" onchange="drawReceipt()"> ${e.name}</label>`).join('')}</div></div><button class="btn" style="width:100%;margin-top:12px" onclick="completeSale()">Complete Sale</button>`;$('#discount').oninput=drawReceipt;$('#seller').onchange=drawReceipt;drawReceipt()}
function drawReceipt(){const r=calcReceipt(),contributors=previewContributors(),sellerId=Number($('#seller')?.value||0),extras=[...document.querySelectorAll('.extraPart:checked')].map(x=>Number(x.value)),participants=[...new Set([sellerId,...contributors.map(c=>c.id),...extras].filter(Boolean))],share=participants.length?Math.floor(r.pool/participants.length):0;$('#receiptPreview').innerHTML=`<h3>${activeBusiness().name}</h3><div class="merchant">Golden Sands Trading Company</div>${cart.map(c=>`<div class="receipt-line"><span>${c.name} × ${c.qty}</span><span>${money(c.price*c.qty)}</span></div>`).join('')}<div class="receipt-line"><span>Sale Amount</span><strong>${money(r.sale)}</strong></div><div class="receipt-line"><span>Company Cut (${state.company.caravanCut}%)</span><strong>${money(r.cut)}</strong></div><div class="receipt-section"><strong>Seller</strong><div class="role-line"><span>${empName(sellerId)}</span><span>Seller</span></div></div><div class="receipt-section"><strong>Stock Contributors</strong>${contributors.length?contributors.map(c=>`<div class="role-line"><span>${c.name}</span><span>${c.units} unit${c.units===1?'':'s'} traced</span></div>`).join(''):'<div class="role-line"><span>None detected</span><span>—</span></div>'}</div><div class="receipt-section"><strong>Additional Participants</strong>${extras.length?extras.map(id=>`<div class="role-line"><span>${empName(id)}</span><span>Added manually</span></div>`).join(''):'<div class="role-line"><span>None</span><span>—</span></div>'}</div><div class="receipt-section"><strong>Profit Split Preview</strong>${participants.map(id=>`<div class="role-line"><span>${empName(id)}</span><span>${money(share)}</span></div>`).join('')}</div><div class="receipt-total"><span>Customer Pays</span><strong>${money(r.sale)}</strong></div>`}
function consumeBatches(item,qty){let need=qty,used=[];for(const b of item.batches){if(need<=0)break;const take=Math.min(need,b.qty);if(take>0){used.push({contributorId:b.contributorId,qty:take,source:b.source});b.qty-=take;need-=take}}item.batches=item.batches.filter(b=>b.qty>0);item.qty-=qty;return used}
window.completeSale=()=>{if(!cart.length)return alert('Add at least one item.');const r=calcReceipt(),sellerId=Number($('#seller').value),extras=[...document.querySelectorAll('.extraPart:checked')].map(x=>Number(x.value)),contribMap=new Map();cart.forEach(c=>{const item=state.inventory.find(i=>i.id===c.id),used=consumeBatches(item,c.qty);used.forEach(u=>contribMap.set(u.contributorId,(contribMap.get(u.contributorId)||0)+u.qty))});const contributorIds=[...contribMap.keys()],participants=[...new Set([sellerId,...contributorIds,...extras])],share=participants.length?Math.floor(r.pool/participants.length):0;participants.forEach(id=>{const e=state.employees.find(x=>x.id===id);if(e)e.earnings+=share});activeBusiness().coffers+=r.cut;state.history.unshift({id:Date.now(),businessId:state.activeBusinessId,date:now(),who:empName(sellerId),detail:cart.map(c=>`${c.name} × ${c.qty}`).join(', '),amount:r.sale,companyCut:r.cut,participants:participants.map(id=>({id,name:empName(id),roles:[id===sellerId?'Seller':null,contributorIds.includes(id)?'Stock Contributor':null,extras.includes(id)?'Additional':null].filter(Boolean)}))});save();cart=[];alert(`Sale recorded.\nCompany cut: ${money(r.cut)}\nEach participant: ${money(share)}`);render()}
function inventory(){setHead('Inventory',activeBusiness().name);$('#pageActions').innerHTML='<button class="btn" onclick="stockIntake()">+ Stock Intake</button><button class="btn ghost" onclick="addItem()">+ New Item</button>';app.innerHTML=`<div class="card">${table(['Item','Condition','Qty','Price','Stock Provenance'],inv().map(i=>`<tr><td><strong>${i.name}</strong></td><td>${i.condition}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${i.batches.map(b=>`${b.qty} by ${empName(b.contributorId)}`).join(' · ')||'—'}</td></tr>`))}</div>`}
window.addItem=()=>modal('Add New Item',`<div class="form-grid"><div class="field span2"><label>Item Name</label><input id="iName" class="input"></div><div class="field"><label>Category</label><input id="iCat" class="input"></div><div class="field"><label>Condition</label><input id="iCond" class="input" value="Standard"></div><div class="field"><label>Sale Price</label><input id="iPrice" type="number" class="input" value="0"></div></div>`,()=>{if(!$('#iName').value.trim())return;state.inventory.push({id:Date.now(),businessId:state.activeBusinessId,name:$('#iName').value.trim(),category:$('#iCat').value||'Misc',condition:$('#iCond').value||'Standard',qty:0,price:Number($('#iPrice').value)||0,batches:[]});save();closeModal();render()})
window.stockIntake=()=>modal('Stock Intake',`<div class="form-grid"><div class="field span2"><label>Item</label><select id="siItem" class="select">${inv().map(i=>`<option value="${i.id}">${i.name} — ${i.condition}</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input id="siQty" type="number" class="input" value="1"></div><div class="field"><label>Employee Adding Stock</label><select id="siEmp" class="select">${eligibleEmployees().map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select></div><div class="field span2"><label>Source / Note</label><input id="siSource" class="input" value="Stock Intake"></div></div>`,()=>{const item=state.inventory.find(i=>i.id===Number($('#siItem').value)),qty=Math.max(1,Number($('#siQty').value)||1),eid=Number($('#siEmp').value);item.qty+=qty;item.batches.push({batchId:'b'+Date.now(),qty,contributorId:eid,source:$('#siSource').value||'Stock Intake'});save();closeModal();render()})
function transfers(){setHead('Transfers','Inter-Business Stock');$('#pageActions').innerHTML='<button class="btn" onclick="newTransfer()">+ Transfer Stock</button>';app.innerHTML=`<div class="card">${table(['Date','Item','Qty','From','To','By','Contributor Trace'],state.transfers.map(t=>`<tr><td>${t.date}</td><td>${t.item}</td><td>${t.qty}</td><td>${t.from}</td><td>${t.to}</td><td>${t.by}</td><td>${t.trace.map(x=>`${x.qty} ${empName(x.contributorId)}`).join(' · ')}</td></tr>`))}</div>`}
window.newTransfer=()=>modal('Transfer Stock',`<div class="form-grid"><div class="field span2"><label>Item</label><select id="trItem" class="select">${inv().map(i=>`<option value="${i.id}">${i.name} (${i.qty})</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input id="trQty" type="number" class="input" value="1"></div><div class="field"><label>Destination</label><select id="trDest" class="select">${state.businesses.filter(b=>b.id!==state.activeBusinessId&&b.status==='Active').map(b=>`<option value="${b.id}">${b.name}</option>`).join('')}</select></div><div class="field span2"><label>Employee Making Transfer</label><select id="trEmp" class="select">${eligibleEmployees().map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select></div></div>`,()=>{const src=state.inventory.find(i=>i.id===Number($('#trItem').value)),qty=Math.max(1,Number($('#trQty').value)||1),dest=$('#trDest').value,eid=Number($('#trEmp').value);if(qty>src.qty)return alert('Not enough stock.');let need=qty,trace=[];for(const b of src.batches){if(need<=0)break;const take=Math.min(need,b.qty);if(take){trace.push({contributorId:b.contributorId,qty:take,source:b.source});b.qty-=take;need-=take}}src.batches=src.batches.filter(b=>b.qty>0);src.qty-=qty;let target=state.inventory.find(i=>i.businessId===dest&&i.name===src.name&&i.condition===src.condition);if(!target){target={...src,id:Date.now(),businessId:dest,qty:0,batches:[]};state.inventory.push(target)}target.qty+=qty;trace.forEach(t=>target.batches.push({batchId:'b'+Date.now()+Math.random(),qty:t.qty,contributorId:t.contributorId,source:`Transfer from ${activeBusiness().name}; original source: ${t.source}`}));state.transfers.unshift({id:Date.now(),date:now(),item:src.name,qty,from:activeBusiness().name,to:bizName(dest),by:empName(eid),trace});save();closeModal();render()})
function notebook(){setHead('Caravan Notebook','In-Character Notices');$('#pageActions').innerHTML='<button class="btn" onclick="newNote()">+ Write Note</button>';app.innerHTML=`<div class="grid g2">${state.notes.filter(n=>n.businessId===state.activeBusinessId).map(n=>`<div class="scroll-card"><span class="eyebrow">${n.date}</span><h3>${n.author}</h3><p>${n.text}</p></div>`).join('')||'<div class="empty">No notes.</div>'}</div>`}window.newNote=()=>modal('Write Note','<div class="field"><label>Notice</label><textarea id="nText" class="textarea"></textarea></div>',()=>{if(!$('#nText').value.trim())return;state.notes.unshift({id:Date.now(),author:"Ko'vash",date:now(),businessId:state.activeBusinessId,text:$('#nText').value.trim(),pinned:false});save();closeModal();render()})
function employees(){setHead('Employees','Company Staff');$('#pageActions').innerHTML='<button class="btn" onclick="addEmployee()">+ Employee</button>';app.innerHTML=`<div class="business-grid">${state.employees.map(e=>`<div class="business-card"><span class="eyebrow">${e.role}</span><h3>${e.name}</h3><p>${e.email}</p>${state.businesses.map(b=>`<div class="supplier-row"><span>${b.name}</span><strong>${e.assignments?.[b.id]?.enabled?'Allowed':'No Access'}</strong></div>`).join('')}<div class="quick" style="margin-top:10px"><button class="btn ghost" onclick="editEmployee(${e.id})">Edit Access</button></div></div>`).join('')}</div>`}
window.addEmployee=()=>modal('Add Employee','<div class="form-grid"><div class="field"><label>Name</label><input id="eName" class="input"></div><div class="field"><label>Google Email</label><input id="eEmail" class="input"></div><div class="field span2"><label>Role</label><input id="eRole" class="input" value="Merchant"></div></div>',()=>{if(!$('#eName').value.trim()||!$('#eEmail').value.trim())return;const assignments={};state.businesses.forEach(b=>assignments[b.id]={enabled:false,permissions:[]});state.employees.push({id:Date.now(),name:$('#eName').value.trim(),email:$('#eEmail').value.trim(),role:$('#eRole').value||'Merchant',earnings:0,assignments});save();closeModal();render()})
window.editEmployee=id=>{const e=state.employees.find(x=>x.id===id);modal('Edit Employee Business Access',`<div class="grid g2">${state.businesses.map(b=>`<div class="assignment-block"><div class="assignment-head"><strong>${b.name}</strong><label><input class="bizEnabled" data-biz="${b.id}" type="checkbox" ${e.assignments?.[b.id]?.enabled?'checked':''}> Can Work Here</label></div><div class="permission-grid">${Object.entries(permissionLabels).map(([k,l])=>`<label class="perm"><input class="bizPerm" data-biz="${b.id}" data-perm="${k}" type="checkbox" ${e.assignments?.[b.id]?.permissions?.includes(k)||e.assignments?.[b.id]?.permissions?.includes('all')?'checked':''}> ${l}</label>`).join('')}</div></div>`).join('')}</div>`,()=>{state.businesses.forEach(b=>{const enabled=document.querySelector(`.bizEnabled[data-biz="${b.id}"]`).checked;const ps=[...document.querySelectorAll(`.bizPerm[data-biz="${b.id}"]:checked`)].map(x=>x.dataset.perm);e.assignments[b.id]={enabled,permissions:ps}});save();closeModal();render()})}
function coffers(){setHead('Coffers',activeBusiness().name);app.innerHTML=`<div class="grid g3">${stat('Current Balance',money(activeBusiness().coffers),'Business funds')}${stat('Company Cut',state.company.caravanCut+'%','Default sale cut','%')}${stat('Company Total',money(state.businesses.reduce((a,b)=>a+b.coffers,0)),'All businesses','¤')}</div>`}function history(){setHead('Sales History','Audit Ledger');app.innerHTML=`<div class="card">${table(['Date','Seller','Items','Sale','Company Cut','Participants'],state.history.filter(h=>h.businessId===state.activeBusinessId).map(h=>`<tr><td>${h.date}</td><td>${h.who}</td><td>${h.detail}</td><td>${money(h.amount)}</td><td>${money(h.companyCut)}</td><td>${h.participants?.map(p=>`${p.name} (${p.roles.join('/')})`).join(' · ')||'—'}</td></tr>`))}</div>`}function earnings(){setHead('Employee Earnings','Profit Distribution');app.innerHTML=`<div class="business-grid">${state.employees.map(e=>`<div class="business-card"><span class="eyebrow">${e.role}</span><h3>${e.name}</h3><div class="stat" style="min-height:0"><div class="value">${money(e.earnings)}</div><div class="sub">Recorded earnings</div></div></div>`).join('')}</div>`}function permissions(){setHead('Permissions','Business-Scoped Access');app.innerHTML='<div class="notice">Permissions are now stored per employee per business. Use Employees → Edit Access to decide where each employee can work and what they can do there.</div>'}function settings(){setHead('Settings','Company Configuration');app.innerHTML=`<div class="card"><h3>Profit Rules</h3><div class="field"><label>Default Company Cut %</label><input id="setCut" class="input" type="number" min="0" max="100" value="${state.company.caravanCut}"></div><button class="btn" style="margin-top:10px" onclick="saveCut()">Save</button></div>`}window.saveCut=()=>{state.company.caravanCut=Math.max(0,Math.min(100,Number($('#setCut').value)||0));save();render()}
function modal(title,body,onSave){$('#modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><h3>${title}</h3>${body}<div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button id="modalSave" class="btn">Save</button></div></div></div>`;$('#modalSave').onclick=onSave}window.closeModal=()=>$('#modalRoot').innerHTML='';
buildNav();buildBusinessSelect();renderNotebookPreview();render();
